server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;

  location = /auth    { return 301 /auth/; }
  location = /profile { return 301 /profile/; }
  location = /survey  { return 301 /survey/; }
  location = /admin   { return 301 /admin/; }

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /auth/    { try_files $uri $uri/ /auth/index.html; }
  location /profile/ { try_files $uri $uri/ /profile/index.html; }
  location /survey/  { try_files $uri $uri/ /survey/index.html; }
  location /admin/   { try_files $uri $uri/ /admin/index.html; }
}
